### ISSUE TITLE
nrf52 Continuous Speech Demo Error: "PDM.h file not found"

### ISSUE THREAD

**Issue by anujdutt9** [adafruit/Adafruit_TFLite_Micro_Speech#4]
**Hardware:** 
Circuit Playground Bluefruit nRF52840 [Cortex M4 processor]

**Issue Description:** 
I am trying to run the "micro_speech_continuous_nrf" demo under "nrf52" directory. I am getting the following error:
```
audio_provider.cpp:17:17: error: PDM.h: No such file or directory

 #include "PDM.h"

                 ^

compilation terminated.

exit status 1
PDM.h: No such file or directory
```
Is the tensorflow lite library missing this file ? I have installed Adafruit's TFLite library from Arduino as well as the other required libraries.
Thanks.

**Comment by ladyada** [comment]
hiya you'll need the master branch of
https://github.com/adafruit/Adafruit_nRF52_Arduino
because we haven't done a board release since adding PDM support!

**Comment by anujdutt9** [comment]
Awesome. Thank you so much. Just one last thing. I have trained a Tensorflow model and saved a TFLite model from that. 
Is there any tutorial present or coming up explaining about how to go from that TFLite model to Arduino/nRF52  or any other platform?
Thanks.

**Comment by ladyada** [comment]
the nrf52 doesn't quite have the drag-n-drop code yet, may be a few weeks
so for now you have to xxd'it into the header file by hand. check the tensorflowlite dox for info!
