### ISSUE TITLE
Trouble installing tensorflow lite speech demo on Pygamer 

### ISSUE THREAD

**Issue by lordbyronxxiv** [adafruit/Adafruit_TFLite_Micro_Speech#6]
I ordered a Pygamer starter kit to test the micro speech, since that is what it was demoed on, this was I believe before the pybadge kit came out. I tried following the directions given with the pybadge setup, I selected Pygamer express for my board, but when I try to compile the example it errors out, I can’t upload it either not sure what I’m doing wrong. I tried uploading another random example and same problem. Do you have to have internet access to upload the examples?

**Comment by ladyada** [comment]
hiya you need to give some more details

**Comment by ladyada** [comment]
hiya this repo will be deprecated because we're now using the official TensorFlow library 
check the guide here for new examples!
https://learn.adafruit.com/tensorflow-lite-for-edgebadge-kit-quickstart/
