### ISSUE TITLE
Error when compiling the code

### ISSUE THREAD

**Issue by yang12313** [adafruit/Adafruit_TFLite_Micro_Speech#7]
Hi,

I received an error when compiling the example code on adafruit Bluefruit nRF52 board. The error message is too long so I posted in the link below:

[https://github.com/yang12313/Adafruit-Tensorflow/tree/master](url)

Is there anyway to solve it?

**Comment by ladyada** [comment]
hiya this repo will be deprecated because we're now using the official TensorFlow library 
check the guide here for new examples!
https://learn.adafruit.com/tensorflow-lite-for-edgebadge-kit-quickstart/
